const LIST_PRODUCT="LIST_PRODUCT"
const BUY_ITEM="BUY_ITEM"
const UPDATE_ITEM="UPDATE_ITEM"
const DELETE_ITEM="DELETE_ITEM"
const CHANGE_NOTIFY='CHANGE_NOTIFY'


export{
    LIST_PRODUCT,
    BUY_ITEM,
    UPDATE_ITEM,
    DELETE_ITEM,
    CHANGE_NOTIFY
}